openapi: 3.0.0
info:
  title: Card Details
  x-version-history:
    1.0.5: 2020-08-10 - Projet CLEW - Modification du format de la date et ne plus considérer la date de validité comme obligatoire
    1.0.4: 2020-07-27 - Projet CLEW - Correction de path de /creditcards/{Id} à /creditcards/cards/{Id} en concordance avec l'architecture
    1.0.3: 2020-07-16 - Projet CLEW - Ajout de champ EligibleOnlineActivation dans l'entité de réponse Cards Ajout de champ CardHolderInfo dans l'entité de réponse ResponseModeInfo
    1.0.2: 2020-06-15 - Projet CLEW - Renommer l'élément AlternateStatus pour PreviousStatus et ajout des éléments StatusCode et PreviousStatusCode. Renommer CardHolder pour Holder.
    1.0.1: 2020-06-03 - Projet CLEW - Ajout de la section Holder
    1.0.0: 2020-05-20 - Projet CLEW - Ajout de l'opération get /creditcards/{Id}
  version: 1.0.5
  description: This API allows an application to get detailed information about a credit card.
  contact:
    name: Gestion de la demande - Domaine Carte
    url: https://jira.bnc.ca/servicedesk/customer/portal/442/group/1229
servers:
- url: https://cards-gateway.ose.cloud.res.bngf.local
  description: Production environment
paths:
  /creditcards/cards/{Id}:
    get:
      tags:
      - Get credit card information
      operationId: GetCreditCardDetail
      parameters:
      - name: Id
        in: path
        description: Reference number associated with a card number
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/x-fapi-auth-date'
      - $ref: '#/components/parameters/x-fapi-customer-ip-address'
      - $ref: '#/components/parameters/x-fapi-interaction-id'
      - $ref: '#/components/parameters/Authorization'
      - $ref: '#/components/parameters/x-idempotency-key'
      - $ref: '#/components/parameters/x-jws-signature'
      - $ref: '#/components/parameters/channel'
      responses:
        '200':
          $ref: '#/components/responses/200CardDetailInfo'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'
        '504':
          $ref: '#/components/responses/504Error'
components:
  parameters:
    x-fapi-auth-date:
      in: header
      name: x-fapi-auth-date
      required: false
      description: 'The time when the PSU last logged in with the TPP. All dates in
        the HTTP headers are represented as RFC 7231 Full Dates. An example is below:
        Sun, 10 Sep 2017 19:43:31 UTC'
      schema:
        type: string
        pattern: ^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} (GMT|UTC)$
    x-fapi-customer-ip-address:
      in: header
      name: x-fapi-customer-ip-address
      required: false
      description: The PSU's IP address if the PSU is currently logged in with the TPP
      schema:
        type: string
    x-fapi-interaction-id:
      in: header
      name: x-fapi-interaction-id
      required: true
      description: An RFC4122 UID used as a correlation id
      schema:
        type: string
    Authorization:
      in: header
      name: Authorization
      required: false
      description: An Authorisation Token as per https://tools.ietf.org/html/rfc6750
      schema:
        type: string
    x-idempotency-key:
      name: x-idempotency-key
      in: header
      description: |
        Every request will be processed only once per x-idempotency-key.  The
        Idempotency Key will be valid for 24 hours.
      required: false
      schema:
        type: string
        pattern: ^(?!\s)(.*)(\S)$
        maxLength: 40
    x-jws-signature:
      in: header
      name: x-jws-signature
      required: false
      description: A detached JWS signature of the body of the payload
      schema:
        type: string
    channel:
      in: header
      name: ChannelName
      required: true
      description: Channel of the consumer
      schema:
        type: string
  schemas:
    OBCardDetailInfoResponse:
      type: object
      required:
      - Data
      properties:
        Data:
          type: object
          required:
          - Cards
          properties:
            ResponseModeInfo:
              $ref: '#/components/schemas/ModeInfoResp'
            Cards:
              type: object
              required:
              - ReferenceId
              properties:
                ReferenceId:
                  description: Reference id associated to a credit card number
                  type: string
                MaskedCardNumber:
                  description: Credit card number that has been masked
                  type: string
                Status:
                  description: Business status of the credit card
                  type: string
                StatusCode:
                  description: Status code of the credit card
                  type: string
                PreviousStatus:
                  description: Previous business status of the credit card
                  type: string
                PreviousStatusCode:
                  description: Previous status code of the credit card
                  type: string
                LastStatusDate:
                  description: Last update status of the credit card
                  type: string
                  format: date
                EligibleOnlineActivation:
                  description: If the credit card can be activated online or not
                  type: boolean
                CardEmbosser:
                  description: Array of card embosser names
                  type: array
                  items:
                    $ref: '#/components/schemas/Embosser'
                CardDetails:
                  $ref: '#/components/schemas/OBCardDetailsInfoResp'
                Holder:
                  $ref: '#/components/schemas/OBCardHolderInfoResp'
    ModeInfoResp:
      type: object
      required:
      - ResponseMode
      - CustomerInfo
      - CardHolderInfo
      properties:
        ResponseMode:
          description: Type of response received from the backend
          type: string
        CustomerInfo:
          description: If the customer information is present or not
          type: string
        CardHolderInfo:
          description: If the card holder information is present or not
          type: string
    Embosser:
      type: object
      properties:
        EmbosserName:
          description: Name on the credit card
          type: string
    OBCardDetailsInfoResp:
      type: object
      properties:
        CardValidityDate:
          description: From what date the credit card is valid - format MM/YY
          type: string
        CardExpirationDate:
          description: The expiration date of the credit card - format MM/YY
          type: string
    OBCardHolderInfoResp:
      type: object
      properties:
        HolderId:
          description: Customer number at the back-end
          type: string
        RoleType:
          description: Role type
          type: string
          enum:
          - CO/DETENT
          - DET/PRINC
        HolderName:
          description: Account owner name
          type: string
    Problem:
      type: object
      properties:
        Id:
          type: string
          description: Correlation ID
        Type:
          type: string
          description: A URI reference [RFC3986] that identifies the problem type.  This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type. When this member is not present, its value is assumed to be [about:blank].
        Title:
          type: string
          description: A short, human-readable summary of the problem type
        Status:
          type: string
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem
        Detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        Instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
        Elements:
          type: array
          items:
            $ref: '#/components/schemas/Element'
      additionalProperties: false
    Element:
      type: object
      properties:
        Id:
          type: string
          description: The ID of the specific element in cause
        Name:
          type: string
          description: The name of the specific element in cause
        SourceCode:
          type: string
          description: The system code of the specific element in cause
        ReasonType:
          type: string
          description: A code identifying the reason why the element is in cause
        ReasonCode:
          type: string
          description: A code identifying the specific reason why the element is in cause
        Message:
          type: string
          description: A short, human-readable summary of the reason-code
        Severity:
          type: string
          description: A code identifying the specific severity of the cause
        Instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the element in cause
        Timestamp:
          type: string
          description: A timestamp identifying the specific occurrence of the element in cause
      additionalProperties: false
  responses:
    200CardDetailInfo:
      description: Card detail information
      headers:
        x-fapi-interaction-id:
          description: An RFC4122 UID used as a correlation id
          schema:
            type: string
        x-jws-signature:
          description: |
            Header containing a detached JWS signature of the body of the payload
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OBCardDetailInfoResponse'
    400Error:
      description: Bad request
      headers:
        x-fapi-interaction-id:
          description: An RFC4122 UID used as a correlation id
          schema:
            type: string
        x-jws-signature:
          description: |
            Header containing a detached JWS signature of the body of the payload
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
    500Error:
      description: Internal Server Error
      headers:
        x-fapi-interaction-id:
          description: An RFC4122 UID used as a correlation id
          schema:
            type: string
        x-jws-signature:
          description: |
            Header containing a detached JWS signature of the body of the payload
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
    504Error:
      description: Timeout
      headers:
        x-fapi-interaction-id:
          description: An RFC4122 UID used as a correlation id
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
